<?php

namespace Database\Seeders;

use App\Models\Credit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CreditSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('credits')->insert([
            'identifiantClient' => 1,
            'codeAgent' => 7,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Achat de terrain',
            'etatCredit' => 'SAINT',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-03-14',
            'derniereEcheance' => '2024-03-14',
            'secteurActivite' => 'Agriculture',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 400000,
            'montantEligible' => 400000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 2,
            'codeAgent' => 8,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Achat de produit cosmétique',
            'etatCredit' => 'CONTENTIEUX',
            'dateDemande' => '2023-03-01',
            'dateDeboursement' => '2023-03-20',
            'dateInitiale' => '2023-04-20',
            'derniereEcheance' => '2024-02-20',
            'secteurActivite' => 'Esthéticienne',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 200000,
            'montantEligible' => 200000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 3,
            'codeAgent' => 9,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Logement',
            'etatCredit' => 'PERTE',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Renovation',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 800000,
            'montantEligible' => 800000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 4,
            'codeAgent' => 10,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Création d\'Emplois',
            'etatCredit' => 'SAINT',
            'dateDemande' => '2023-02-01',
            'dateDeboursement' => '2023-02-10',
            'dateInitiale' => '2023-03-10',
            'derniereEcheance' => '2023-12-10',
            'secteurActivite' => 'Entrepreneur',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 1000000,
            'montantEligible' => 1000000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 5,
            'codeAgent' => 11,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Capital de Roulement',
            'etatCredit' => 'SAINT',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-03-14',
            'secteurActivite' => 'Entrepreneur',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 1200000,
            'montantEligible' => 1200000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 6,
            'codeAgent' => 12,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Agriculture et Élevage',
            'etatCredit' => 'PERTE',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Agriculture et Élevage',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 350000,
            'montantEligible' => 350000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 7,
            'codeAgent' => 7,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Soins de Santé',
            'etatCredit' => 'IMMOBILISE',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Immobilier',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 250000,
            'montantEligible' => 250000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 8,
            'codeAgent' => 8,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Achat de Materiel',
            'etatCredit' => 'IMMOBILISE',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Developeur',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 300000,
            'montantEligible' => 300000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 9,
            'codeAgent' => 9,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Achat de véhicules neufs ou d\'occasion',
            'etatCredit' => 'CONTENTIEUX',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Automobile',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 2000000,
            'montantEligible' => 2000000,
        ]);
        DB::table('credits')->insert([
            'identifiantClient' => 10,
            'codeAgent' => 10,
            'codeBureau' => 27,
            'codeProduit' => 1,
            'objetCredit' => 'Achat de piece automobile',
            'etatCredit' => 'SAINT',
            'dateDemande' => '2023-05-01',
            'dateDeboursement' => '2023-05-14',
            'dateInitiale' => '2023-06-14',
            'derniereEcheance' => '2024-04-14',
            'secteurActivite' => 'Mecanique',
            'nombreEcheance' => 10,
            'nombreDiffereCapitale' => 0,
            'nombreDiffereInteret' => 0,
            'uniteDiffere' => 0,
            'montantAccorde' => 2000000,
            'montantEligible' => 2000000,
        ]);
    }
}
